# Generated by Django 2.0.4 on 2018-04-20 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20180420_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.Employee'),
            preserve_default=False,
        ),
    ]
